engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/