before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
php: 
  - 5.5
  - 5.6
  - 7.0
language: php
addons:
  code_climate:
      repo_token: a7af885a16b3103a0ce942e29de04bd038b5409299da586dce821a3e55c1dfed